# Generated by Django 2.0.2 on 2018-02-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_catalog', '0002_auto_20180219_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/assets/items'),
        ),
    ]
