# Generated by Django 2.0.2 on 2018-02-19 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_catalog', '0003_auto_20180219_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicName',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('id_modification', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car_catalog.Modification')),
            ],
        ),
        migrations.CreateModel(
            name='CharacteristicValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
                ('unit', models.CharField(blank=True, max_length=128, null=True)),
                ('id_characteristicName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_catalog.CharacteristicName')),
            ],
        ),
        migrations.RemoveField(
            model_name='characteristic',
            name='id_modification',
        ),
        migrations.AlterField(
            model_name='car',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_catalog.Category'),
        ),
        migrations.AlterField(
            model_name='car',
            name='id_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_catalog.Mark'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to='item_pics'),
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
    ]
